Bibi.preset({
  'bookshelf': '../../books',
  'reader-view-mode': 'paged',
  'full-breadth-layout-in-scroll': 'no',
  'fix-reader-view-mode': 'yes',
  'keep-settings': 'yes',
  'resume-from-last-position': 'yes',
  'autostart': 'yes',
  'autostart-embedded': 'yes',
  'start-embedded-in-new-window': 'no',
  'use-menubar': 'yes',
  'use-full-height': 'no',
  'use-arrows': 'yes',
  'flipper-width': 0.2,
  'use-keys': 'yes',
  'use-slider': 'yes',
  'flip-pages-during-sliding': 'yes',
  'use-nombre': 'yes',
  'use-font-size-changer': 'yes',
  'base-font-size': 'auto',
  'font-size-scale-per-step': 1.15,
  'use-loupe': 'desktop',
  'loupe-max-scale': 4,
  'loupe-scale-per-step': 1.6,
  'zoom-out-for-utilities': 'yes',
  'use-history': 'yes',
  'max-history': 19,
  'use-bookmarks': 'yes',
  'max-bookmarks': 9,
  'orientation-border-ratio': 1.33,
  'ui-font-family': "Inter, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif",
  'item-padding-left': 24,
  'item-padding-right': 24,
  'item-padding-top': 40,
  'item-padding-bottom': 24,
  'spread-gap': 40,
  'spread-margin': 0,
  'fix-nav-ttb': 'no',
  'content-draggable': [true, true],
  'orthogonal-arrow-keys': ['move', 'switch'],
  'orthogonal-edges': ['utilities', 'utilities'],
  'orthogonal-touch-moves': ['move', 'switch'],
  'orthogonal-wheelings': ['move', 'across'],
  'extensions': [],
  'website-name-in-title': '叶读 · LeafRead',
  'website-name-in-menu': '返回叶读首页',
  'website-href': new URL('/', location.href).href,
  'remove-bibi-website-link': true,
  'extract-if-necessary': ['.epub'],
  'default-page-progression-direction': 'ltr',
  'accept-local-file': 'yes',
  'accept-bibizine': false,
  'accept-blob-converted-data': false,
  'accept-base64-encoded-data': false,
  'pagination-method': 'auto',
  'allow-placeholders': true,
  'prioritise-fallbacks': false,
  'allow-scripts-in-content': false,
  'trustworthy-origins': [],
  'bibi': 'EPUB Reader on your website.',
});
